title: Java on ACA
description: This lab walks you through the creation of a Java application on Azure Container Apps integrated with multiple Azure services
theme: just-the-docs

# url: https://Azure-Samples.github.io/java-on-aca

aux_links:
  "Java on ACA lab on GitHub": 
    - "https://github.com/Azure-Samples/java-on-aca"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
